---
title: "EDAmigo Interactive Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
params:
  
  x: c(1,2)
  y: c(1,2)
  pie: c(1,2)
  box: c(1,2)

---

```{r setup, include=FALSE}
library(flexdashboard)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Proof of Concept!

```{r}
plotly::plot_ly(x = params$x, y = params$y, mode = "markers") %>%
  layout(title = "Interactive Scatter Plot", xaxis = list(title= 'X label to be updated'), yaxis = list(title = 'y label to be updated'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
plotly::plot_ly(params$pie, labels = ~term, values = ~loan_amnt, type = 'pie') %>% layout(title = 'Example Pie Chart',  
        xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)) 
```

### Chart C


```{r}
plotly::plot_ly(x = params$box$term[params$box$term=='36 months'] , y= params$box$funded_amnt, type = 'box', name ="36 Months") %>% layout(title = "Box Plots") %>% add_trace(x =params$box$term[params$box$term=='60 months'], name ="60 Months")
```

